services:
  # Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_app
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Laravel Backend
  backend:
    build:
      context: ./back-end
      dockerfile: dockerfiles/php.dockerfile
      args:
        UID: 1000
        GID: 1000
        USER: laravel
    volumes:
      - ./back-end:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_app
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network

  # Nginx for Laravel
  nginx:
    build:
      context: ./back-end
      dockerfile: dockerfiles/nginx.dockerfile
      args:
        UID: 1000
        GID: 1000
        USER: laravel
    ports:
      - "8000:80"
    volumes:
      - ./back-end:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

  # Next.js Frontend
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      APP_NAME: "CLMS"
      BACKEND_API_HOST: http://nginx
      SECRET_COOKIE_PASSWORD: okp2oJszqs/cgn+NQhIQ+Q9JCMHHUG/yVgHnqP09u2k=
    depends_on:
      - nginx
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
