name: Frontend Code Quality and Testing

on:
  push:
    branches: [main, develop]
    paths:
      - "front-end/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "front-end/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  # Job 1: Frontend Code Quality & Testing
  frontend-quality:
    name: Frontend Code Quality & Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: front-end/package-lock.json

      - name: Install Frontend dependencies
        working-directory: ./front-end
        run: npm ci

      - name: Run Frontend lint check
        working-directory: ./front-end
        run: npm run lint || echo "⚠️ Linting issues found - continuing anyway"

      - name: Build Frontend application
        working-directory: ./front-end
        run: npm run build
        env:
          SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD }}

      - name: Test Frontend Dockerfile
        run: |
          echo "✅ Checking Frontend Dockerfile..."
          docker build --no-cache -f front-end/Dockerfile front-end --dry-run 2>/dev/null || docker build -t test-frontend -f front-end/Dockerfile front-end --build-arg SECRET_COOKIE_PASSWORD="${{ secrets.SECRET_COOKIE_PASSWORD }}"

  # Job 2: Discord Success Notification for Code Quality
  notify-discord-quality-success:
    name: Discord Code Quality Success
    runs-on: ubuntu-latest
    needs: [frontend-quality]
    if: success()

    steps:
      - name: Discord Quality Success Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          title: "✅ Frontend Code Quality Passed!"
          description: |
            **Frontend code quality checks completed successfully!**
            
            **✅ Achievements:**
            • Dependencies installed
            • Lint checks passed
            • Build successful
            • Dockerfile validated
            
            **Build Details:**
            • Branch: `${{ github.ref_name }}`
            • Commit: `${{ github.sha }}`
            • Workflow: ${{ github.workflow }}
          color: 0x00ff00
          username: "GitHub Actions - Quality"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

  # Job 3: Discord Failure Notification for Code Quality
  notify-discord-quality-failure:
    name: Discord Code Quality Failure
    runs-on: ubuntu-latest
    needs: [frontend-quality]
    if: failure()

    steps:
      - name: Discord Quality Failure Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: "❌ Frontend Code Quality Failed!"
          description: |
            **Frontend code quality checks failed!**
            
            **Common Issues:**
            • Linting errors
            • Build failures
            • Dependency issues
            • Dockerfile problems
            
            **Build Details:**
            • Branch: `${{ github.ref_name }}`
            • Commit: `${{ github.sha }}`
            • Workflow: ${{ github.workflow }}
            
            Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
          color: 0xff0000
          username: "GitHub Actions - Quality"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
