name: Frontend Code Quality and Testing

on:
  push:
    branches: [main, develop]
    paths:
      - "front-end/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "front-end/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  # Job 1: Frontend Code Quality & Testing
  frontend-quality:
    name: Frontend Code Quality & Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: front-end/package-lock.json

      - name: Install Frontend dependencies
        working-directory: ./front-end
        run: npm ci

      - name: Run Frontend lint check
        working-directory: ./front-end
        run: npm run lint || echo "⚠️ Linting issues found - continuing anyway"

      - name: Build Frontend application
        working-directory: ./front-end
        run: npm run build
        env:
          SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD }}

      - name: Test Frontend Dockerfile
        run: |
          echo "✅ Checking Frontend Dockerfile..."
          docker build --no-cache -f front-end/Dockerfile front-end --dry-run 2>/dev/null || docker build -t test-frontend -f front-end/Dockerfile front-end --build-arg SECRET_COOKIE_PASSWORD="${{ secrets.SECRET_COOKIE_PASSWORD }}"
